### ISSUE TITLE
MPD: adding a bunch of packages

### ISSUE THREAD

**Issue by cemkeylan** [kisslinux/community#409]
Okay, so I am adding mpd (music player daemon) along with some other things. This is a meta issue.

- [X] boost ( dependency for mpd )  #410 
- [ ] mpd  #411 
- [ ] mpc ( C client for mpd )  #413 
- [ ] libmpdclient ( Dependency for mpd clients )  #412 
- [ ] vimpc ( An mpd client with vi-like controls )  #414 

**NOTE:** I didn't add any audio libraries as depends as mpd still builds without any of them.
