### ISSUE TITLE
Libressl update inbound.

### ISSUE THREAD

**Issue by cemkeylan** [kisslinux/community#656]
Dylan is not here at the moment, but a libressl update was released. And it requires a rebuild for some packages. It is a good idea to create PRs to bump the release numbers, so everybody has an overall smoother update experience when Dylan is back and he updates the KISS repository.

Keep in mind that not every package that depends on libressl break. ~`curl`~ and `busybox wget`, for example, are working fine for me.

Here is a list of packages that DO require a rebuild.

- [ ] `lynx` - @dzove855 
- [x] `isync` - @dylanaraps 
- [ ] `mutt` - @penguin-ff 
- [x] ~`glib-networking` - @cemkeylan #657~ Merged
- [x] `glib-networking` - @cemkeylan #670 
- [x] `w3m` - @trbednarzyk
 - [x] `transmission-daemon` - @dylanaraps 

Here is a list of packages that explicitly depend on libressl. I don't know whether these packages do require a rebuild, the package maintainers would be more knowledgable about this.

- [x] `aria2` - @dylanaraps 
- [x] `cyrus-sasl` - @penguin-ff #737 
- [x] `irssi` - @konimex  #658
- [x] `opusfile` - @dylanaraps 
- [x] `socat` - @aaronNGi #672
- [x] `tor` - @IslandAlpha  #677
- [x] `xmlsec1` - @artemkobets  #659 
- [x] `zathura-pdf-mupdf` - @dylanaraps 

There might be packages that do not explicitly depend on libressl, but break because of it. If you know any, I'll add them to this list.

EDIT: It does actually break the libraries of `curl`, but not the program itself.

**Comment by ioraff** [comment]
Just FYI, I'm unable to maintain these at the moment as my machine is having problems--I won't be able to replace it for over a month. I notified Dylan, and he was maintaining mine in the interim.

Thanks for the this nonetheless.

**Comment by aaronNGi** [comment]
Once dylan is back to accept all the pull requests, I will bump `socat`.

**Comment by dylanaraps** [comment]
I'll get onto this shortly. :+1: 

Thanks everyone.

**Comment by cemkeylan** [comment]
Ping @aaronNGi @dzove855 @penguin-ff @IslandAlpha

**Comment by dylanaraps** [comment]
NOTE: ```
The latest stable release is 3.0.2.
The latest development release is 3.1.0.
```

We will wait for the `3.1.X` release before we bump libressl. :+1:

**Comment by eudaldgr** [comment]
`rtorrent` was broken with the last `libressl` bump.
