### ISSUE TITLE
Outdated Packages

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#741]
We've hit 25 outdated packages in Community. It's reached a stage where I feel the need to open a tracker issue to nudge things in the right direction. (I myself have left a package outdated as well).

I understand that everyone's world is currently a flipped upside down and I am willing to take over the maintenance of anyone's packages if they are currently unable to do so. Just let me know. It's no issue at all.

Similarly, if there is a build error or issue related to the update (which you haven't been able to fix), let me know and we'll work on it together.

I will not be accepting any new packages from maintainers with outdated ones. The number is still manageable and I'd like not for it to grow to a bigger scale.

Thanks everyone!

- [x] boost `1.72.0 -> 1.73.0` @cemkeylan 
- [x] ccls `0.20190823.5 -> 0.20190823.6` @trbednarzyk 
- [x] entr `4.4 -> 4.5` @abbbi
- [ ] fd `7.5.0 -> 8.0.0` @kiedtl 
- [x] fish `3.1.0 -> 3.1.2` @onodera-punpun 
- [x] freerdp ` 2.0.0-rc4 ->  2.0.0` @onodera-punpun
- [x] glm `0.9.9.5 -> 0.9.9.8` @onodera-punpun 
- [x] icu `66.1 -> 67.1` @dylanaraps 
- [x] json-c `0.13.1 -> 0.14` @konimex (awaiting cryptsetup)
- [x] msmtp `1.8.8 -> 1.8.10` @Vouivre 
- [x] nss `3.51 -> 3.51.1` @periish 
- [x] osh `0.8.pre3 -> 0.8.pre4` @jedahan 
- [x] picom `7.5 -> 8.0` @konimex 
- [x] poppler `0.87.0 -> 0.88.0` @Vouivre 
- [x] cython `0.29.16 -> 0.29.17` @ioraff (updated by @dylanaraps)
- [x] qemu `4.2.0 -> 5.0.0` @jedavies-dev 
- [x] sinit `1.0 -> 1.1` @cemkeylan (can we find a dist tarball???)
- [x] syncthing `1.4.0 -> 1.4.2` @Bridouz 
- [x] tmux `3.0a -> 3.1a` @konimex
- [x] xmlsec `1.2.29 -> 1.2.30` @artemkobets 
- [x] xwallpaper `0.6.4 -> 0.6.5` @ioraff (updated by @dylanaraps)

**Comment by konimex** [comment]
Due to changes in `json-c`, I cannot upgrade it until `cryptsetup` has a new version.

**Comment by cemkeylan** [comment]
I have mailed Dimitris (the maintainer of sinit) a few months ago for tarball creation but didn't receive any feedback. If I remember correctly, Michael said that 1.1 wasn't that important for Linux.

I actually do have a [1.1 dist tarball here](https://dl.carbslinux.org/distfiles/sinit-1.1.tar.gz), but others in IRC suggested for sticking to the original source.

**Comment by dylanaraps** [comment]
Let's go ahead and use your source. We've tried going to the maintainer to no avail so it's fine to take matters into our own hands now.

**Comment by dylanaraps** [comment]
@konimex There are two commits you could apply (can be merged into a single patch too).

- https://github.com/mbroz/cryptsetup/commit/604abec333a0efb44fd8bc610aa0b1151dd0f612
- https://github.com/mbroz/cryptsetup/commit/e6a356974330e3ae21579a5737976e9a2aad1b51

I don't know how often they release but it seems to me like we're overdue for a cryptsetup update so I'd leave it. :+1:

**Comment by aicsx** [comment]
scrot original project Is stopped at stable 0.8, next release are fork. it's no avaiable from original devel. 

Bind Is full work, at release 17.1 have issue. 
libuv Is related to the above.

we must provide functional and stable packages even if in the devel branch as bond version 17.0 or provide a constantly updated system.  I would like to know, seriously to understand how to regulate myself.

**Comment by dylanaraps** [comment]
> scrot original project Is stopped at stable 0.8, next release are fork. it's no avaiable from original devel. i know original project and I provided that package, not the subsequent holes.

Yes. I forgot that we discussed this.

> we must provide functional and stable packages even if in the devel branch as bind version 17.0 ? or provide a constantly updated system. I would like to know, seriously to understand how to regulate myself.

This is fine. We should stick to regular/stable releases unless there's a reason not to.

> no coincidence that I released the version 17.0 of bind even though it was in devel because I had tested the actual functionality.

This is what confused me about bind.

All in all, I agree with you and I'll remove your packages from the list.

**Comment by aicsx** [comment]
thank you bro. i was sure you would listen to my motives.

**Comment by onodera-punpun** [comment]
I'm running into some probems with the new freerdp version, and glm has some serious issues (see https://github.com/kisslinux/community/pull/634), will try to update everything soon, besides glm.

**Comment by dylanaraps** [comment]
@onodera-punpun What you can do is include `glm`  (the last working version) in the sources (of slop) and statically compile it. We can then drop it from the repositories (I'd much rather nothing else depend on it).

**Comment by dylanaraps** [comment]
@onodera-punpun This works for me:

```sh
#!/bin/sh -e

export DESTDIR="$1"

(
    cd glm
    export DESTDIR="$PWD"

    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_BUILD_TYPE=Release \
        -DSLOP_OPENGL=False

    cmake --build   build
    cmake --install build
)

cmake -B build \
    -DGLM_INCLUDE_DIR="$PWD/glm/usr/include" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DSLOP_OPENGL=False

cmake --build   build
cmake --install build
```

```
https://github.com/naelstrof/slop/archive/v7.5.tar.gz
https://github.com/g-truc/glm/archive/0.9.9.5.tar.gz glm
```

**Comment by dylanaraps** [comment]
@onodera-punpun Freerdp (latest version) builds for me with:

```sh
#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DCHANNEL_URBDRC=OFF

cmake --build   build
cmake --install build
```

**Comment by onodera-punpun** [comment]
Will be creating PR's this afternoon.

**Comment by dylanaraps** [comment]
Thanks everyone. Things are back to a manageable state. :+1:
