### ISSUE TITLE
Outdated packages 

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#867]
This amount is growing once again to a level I'm not entirely pleased with. The aim of this issue is to
update packages which have been going stale and to bring the number down to a sensible level.

- [x] `bind` @aicsx 
- [x] `btrfs-progs` @aicsx 
- [x] `cryptsetup` @konimex
- [ ] `fd` @kiedtl 
- [x] `feh` @konimex 
- [x] `glib-networking` @cemkeylan 
- [x] `hyperfine` @kiedtl 
- [x] `libgpg-error` @a-schaefers 
- [x] `libuv` @aicsx 
- [ ] `loksh` @aaronNGi 
- [ ] `mutt` @penguin-ff 
- [ ] `nnn`  @Iieu 
- [x] `nss` @periish 
- [x] `ripgrep` @kiedtl 
- [x] `syncthing` @Bridouz 
- [x] `tokei` @kiedtl 

See: https://repology.org/projects/?inrepo=kiss_community&outdated=1 for version numbers etc.

**Comment by periish** [comment]
NSS resolved by #886

**Comment by aaronNGi** [comment]
As mentioned in IRC, I'd prefer if we could delete `loksh` in favor of `oksh`.

**Comment by dylanaraps** [comment]
@aaronNGi Sure thing. I await your PRs. :)

**Comment by dylanaraps** [comment]
Thanks everyone. This is back to a nicer number.

**Comment by aaronNGi** [comment]
> @aaronNGi Sure thing. I await your PRs. :)

Done. Sorry, somehow me simply making a pull request which deletes the package didn't cross my mind.
