### ISSUE TITLE
Outdated Packages

### ISSUE THREAD

**Issue by dylanaraps** [kisslinux/community#980]
These packages are currently out of date, the number has once again grown to a  level I'm not entirely pleased with. Let's reduce this number! If you are unable to update your packages due to offline circumstances, please let me know and I will temporarily take over maintenance of your packages. 

- [ ] `bind` @aicsx 
- [ ] `btrfs-progs` @aicsx 
- [ ] `bitfetch` @bit9tream 
- [x] ~~`caddy` @onodera-punpun~~ 
- [x] ~~`entr` @abbbi~~
- [x] ~~`hexyl` @kiedtl~~ 
- [ ] `lua` @dzove855 
- [x] ~~`mercurial` @Himmalerin~~
- [x] ~~`mit-scheme` @DevonMorris~~
- [ ] `nfs-utils` @djt3 
- [x] ~~`nss` @periish~~ 
- [x] ~~`poppler` @Vouivre~~
- [x] ~~`popt` @ioraff Temporarily adopted by me.~~ 
- [ ] `rpcsvc-proto` @djt3 
- [x] ~~`shadow` @a-schaefers~~ Repology is wrong!
- [x] ~~`tokei` @kiedtl~~ 

I am also orphaning the following packages. I took these under my wing when maintainers either disappeared or could no longer maintain them. Some, I personally have no use for any longer. Please adopt these if they are of interest to you.

- [x] ~~ethtool~~ Dropped from Community.
- [x] ~~harfbuzz-icu~~ @cemkeylan 
- [x] ~~icu~~ @cemkeylan 
- [x] ~~intel-media-driver~~ Dropped from Community.
- [x] ~~isync~~ @cemkeylan 
- [x] ~~libevent~~ @konimex 
- [x] ~~libnl @cemkeylan~~ Dropped from Community. 
- [x] ~~mupdf @IslandAlpha~~
- [x] ~~nano~~ @cemkeylan 
- [x] ~~nmap~~ @cemkeylan 
- [x] ~~ntfs-3g~~ @konimex 
- [x] ~~openbox~~ Dropped from Community.
- [x] ~~cython~~ Dropped from Community.
- [x] ~~setroot @onodera-punpun~~
- [x] ~~transmission @onodera-punpun~~ 
- [x] ~~xwallpaper @djt3~~
- [x] ~~youtube-dl (*I'd rather drop this and keep the -git package only*). @Vouivre~~
- [x] ~~zathura-pdf-mupdf @IslandAlpha~~ 
- [x] ~~pandoc-bin @cemkeylan~~
- [x] ~~opusfile~~ Dropped from Community.

**Comment by a-schaefers** [comment]
Shadow is not outdated. Thanks.

**Comment by dylanaraps** [comment]
You would be correct, apologies.

**Comment by konimex** [comment]
Please note that `icu` is needed by `harfbuzz-icu`, which in turn is needed by `webkit2gtk`. @cemkeylan may want to maintain these.

**Comment by cemkeylan** [comment]
Hmm, I would like to order

- `{harfbuzz-,}icu`
- `nano`
- `isync`
- `nmap`

**Comment by cemkeylan** [comment]
I can also take `libnl`.

Also, you forgot to mark `nano`

**Comment by dylanaraps** [comment]
Nothing seems to depend on `libnl`. It should be fine to drop entirely if you like.

**Comment by cemkeylan** [comment]
Oh, I have packages that depend on my repository, but I also have `libnl` on my core repository. If no packages depend on it on community, I think it can be dropped.

**Comment by sdsddsd1** [comment]
somehow related: opusfile has lived, and will live on in kiss-games.

**Comment by dylanaraps** [comment]
Feel free to adopt `opusfile` in Community if you like. :+1:

**Comment by sdsddsd1** [comment]
Since nothing depends on it and I dont have a usecase for it than for the game repo, I feel better when it lives there.

**Comment by onodera-punpun** [comment]
What root setter do you use @dylanaraps?

**Comment by onodera-punpun** [comment]
I'd like to adopt `transmission`.

**Comment by dylanaraps** [comment]
@onodera-punpun `xsetroot` in `kisslinux/repo/xorg/xsetroot`. I also use `imagemagick`'s `display` for setting images as the wallpaper though it's been over a month since I've used even this. I merely set a color as the background nowadays.

**Comment by onodera-punpun** [comment]
Then I'd like to adopt `setroot` as well.

**Comment by dylanaraps** [comment]
Simply send a pull request identical to #981 to transfer ownership. :+1:

**Comment by kiedtl** [comment]
I'm currently unable to update my packages as my KISS laptop seems to have finally breathed its last. I'm looking into getting another machine, but in the meantime I can't do anything.

**Comment by kiedtl** [comment]
I'd definitely appreciate it if someone temporarily took maintainership of my packages -- I'll try to get back to them as soon as possible.

**Comment by dylanaraps** [comment]
Hello @kiedtl, as mentioned in my email to you roughly 2 weeks ago, you should be able to update your packages from a KISS chroot (*which works under any Linux distribution*). This is of course assuming that you have another device running a Linux distribution. If this is not the case, I'm happy to adopt your packages until you are able to once again.  Let me know. :+1:

**Comment by Himmalerin** [comment]
About to send in a PR for mercurial.

For youtube-dl I wrote a [custom build file](https://github.com/Himmalerin/kiss-himmalerin/blob/master/modified/youtube-dl/build) since I didn't like what the existing one was doing. I'm willing to maintain it using my build file or you can drop it and use the -git version

**Comment by dylanaraps** [comment]
@Himmalerin Sure, happy to use your build file. :+1:

**Comment by DevonMorris** [comment]
@dylanaraps I put up a PR for `mit-scheme` sorry for letting that get behind

**Comment by cemkeylan** [comment]
Since nobody is asking for it, I can maintain `pandoc` as well.

**Comment by aicsx** [comment]
I apologize, health problems, I will try to update them as soon as possible

**Comment by dylanaraps** [comment]
No problem. Take all the time you need. Let me know if you'd like me to take over maintenance for the time being.

**Comment by IslandAlpha** [comment]
I can take `zathura-pdf-mupdf` and `libmupdf` (which I think is what you meant by mupdf, mupdf the application isn't in the repos). I already have a good amount of the deps for these packages anyways.

**Comment by dylanaraps** [comment]
Thanks!

**Comment by Vouivre** [comment]
I could be interested by `youtube-dl`. Why would you prefer to keep only a git package ?

**Comment by dylanaraps** [comment]
@Vouivre It sees rather frequent updates. If you're using the `-git` package you're likely to only update it when the sites you use break in the current version (but are likely fixed in git master). I'm fine either way. If you'd like to adopt it, go for it.

**Comment by Himmalerin** [comment]
My Kiss system is currently down so I'm in no position to take over maintaining it, if you're interested in using my build file instead of the current one feel free!

**Comment by Vouivre** [comment]
If nobody else is interested by maintaining `youtube-dl`, I can try. I'm not sure for the moment I will be able to keep it up to date if the updates are coming every three days. Otherwise it should be ok.

**Comment by djt3** [comment]
you can put me down as the maintainer for xwallpaper, ill be using kiss for the foreseeable future so im happy to maintain it.

**Comment by Vouivre** [comment]
If it's ok for you, I created the PR https://github.com/kisslinux/community/pull/1018 to get notifications of new versions of youtube-dl.

**Comment by dylanaraps** [comment]
The number of outdated packages has grown since opening this issue. Please take a look at this page: https://repology.org/projects/?inrepo=kiss_community&outdated=1

**Comment by abbbi** [comment]
> The number of outdated packages has grown since opening this issue. Please take a look at this page: https://repology.org/projects/?inrepo=kiss_community&outdated=1

not sure about libpcap here, seems that site refers to the latest development version? The libpap package in kiss is based on latest release version, which is known to work correctly with the latest tcpdump release version. I dont think im going to update the library to the dev version, maybe producing some issues which tcpdump not working correctly anymore.

**Comment by mcpcpc** [comment]
> The number of outdated packages has grown since opening this issue. Please take a look at this page: https://repology.org/projects/?inrepo=kiss_community&outdated=1

The `kc` package in repology is different than what is in the KISS repo

**Comment by mmatongo** [comment]
`intel-media-driver `
`libnl `

I'll take these up and a few others if they aren't picked up by tomorrow.

**Comment by dylanaraps** [comment]
These were dropped yesterday. You will have to submit them as new packages. Check the git history to find them. :+1:

**Comment by mmatongo** [comment]
Alright

**Comment by mmatongo** [comment]
I can take over Lua as well

**Comment by mmatongo** [comment]
@dylanaraps is lua unmaintained as well, cause I have a branch ready to be pushed if it is.

**Comment by dylanaraps** [comment]
Thanks everyone!
